requires 'Dancer';
requires 'Dancer::Plugin::Thumbnail';
requires 'Net::IMAP::Simple';
requires 'Email::MIME';
requires 'File::Temp';
requires 'Path::Tiny';
requires 'Template';
requires 'Text::Markdown';
requires 'YAML';
